### ISSUE TITLE
Provide the content of the imprint page

### ISSUE THREAD

**Issue by sgehrig** [IISHF/web2019#26]
Provide the content of the imprint page.

**Comment by andrepoddubny** [comment]
How do I change the "imprint" section? There is no menu item for it. 
You and I agreed that we name the photographers, David Stemer and Mauricette Schnider, there.

**Comment by sgehrig** [comment]
@andrepoddubny Just provide the content here in the issue. As discussed earlier, the imprint page is a static page.

**Comment by sgehrig** [comment]
@andrepoddubny What's the status of this issue?

**Comment by andrepoddubny** [comment]
[IISHF  - Imprint.docx](https://github.com/IISHF/web2019/files/6568081/IISHF.-.Imprint.docx)

Here it comes Stefan. As to me, phase 1 is complete once you update the news. We could then publish the site.
