### ISSUE TITLE
Provide the content of the privacy policy page

### ISSUE THREAD

**Issue by sgehrig** [IISHF/web2019#27]
Provide the content of the privacy policy page

**Comment by andrepoddubny** [comment]
Dear Stefan, 

the IISHF Presidium just approved the attached IISHF Data & Privacy Policy. In also includes "Cookies" (issue #28)

[IISHF_Data Privacy Policy_2021-04-07.docx](https://github.com/IISHF/web2019/files/6272508/IISHF_Data.Privacy.Policy_2021-04-07.docx)

**Comment by sgehrig** [comment]
Done
