### ISSUE TITLE
Provide the content for the about sport page

### ISSUE THREAD

**Issue by sgehrig** [IISHF/web2019#29]
Provide the content for the about sport page.

**Comment by andrepoddubny** [comment]
Hello Stefan, I can't enter any information in "about sport" nor the "social media" profiles or the "slider". Please make this available on the backend. Thank you.

**Comment by sgehrig** [comment]
As described in https://github.com/IISHF/web2019/issues/14#issuecomment-774441487 all of these elements are static content. You need to provide the content and I'll add it to the site.

**Comment by andrepoddubny** [comment]
[Skater Hockey.docx](https://github.com/IISHF/web2019/files/6052468/Skater.Hockey.docx)

Please find the description of skater hockey attached.

**Comment by sgehrig** [comment]
@andrepoddubny if you can get me 2 or three new pictures for the page, we can consider that done.

**Comment by andrepoddubny** [comment]
![IMG_8651](https://user-images.githubusercontent.com/41113334/109378875-9868a600-78de-11eb-81f0-2adfe4cc4487.jpg)
![NQ3A2159](https://user-images.githubusercontent.com/41113334/109378879-9f8fb400-78de-11eb-87d2-dfa244aeb1b5.jpg)
![NQ3A6412](https://user-images.githubusercontent.com/41113334/109378882-aa4a4900-78de-11eb-8a37-188b959e16b1.jpg)
![NQ3A6607](https://user-images.githubusercontent.com/41113334/109378886-ae766680-78de-11eb-88f0-2b6569cb41ff.jpg)

**Comment by sgehrig** [comment]
@andrepoddubny And we need a "teaser" text for the homepage. Currently it says

> Roller hockey was born a few decades ago. Only at that time the wheels in the rollers were arranged in two rows, and such a vehicle for movement was called Quad. This sport was called differently, but most often you could hear about rink hockey. Such roller hockey has become widespread in 60 countries, and even up to this point they continue to play it.

**Comment by andrepoddubny** [comment]
Skater Hockey 

is a very fast, physical, dynamic, strategic team sport played on inline or quad skates by two teams consisting of 5 players on the pitch each, usually 4 outfield players and 1 goalkeeper. Skater hockey is played on a small rink on all flat surfaces allowing gym halls to serve as boards. The sport strive to be very accessible and affordable.

**Comment by andrepoddubny** [comment]
Skater Hockey 

is a very fast, physical, dynamic, strategic team sport played on inline or quad skates by two teams consisting of 5 players on the pitch, usually 4 outfield players and 1 goalkeeper. Skater hockey is played on a small rink (standard 20 x 40m) on all flat surfaces allowing gym halls to serve as boards. The sport strives to be very accessible and affordable.

**Comment by andrepoddubny** [comment]
Hatte da noch zwei Fehler drin.
