### ISSUE TITLE
Come up with an idea for the top slider on the homepage

### ISSUE THREAD

**Issue by sgehrig** [IISHF/web2019#30]
Currently the homepage's top slider shows the same content for all slides. I have no idea what was the designer's idea with that slider.

**Comment by sgehrig** [comment]
<img width="1083" alt="Bildschirmfoto 2021-02-06 um 11 41 01" src="https://user-images.githubusercontent.com/43394/107115918-333a0b80-6870-11eb-81c7-376a2e29897b.png">

**Comment by andrepoddubny** [comment]
Dear Stefan, i would put a mix from news, tournaments, our vision, the mission, our values and certain goals on this slider. Obviously we need to change pictures for every bullet. 

[2021-02-27_ IISHF Vision, Mission, Values_updated.docx](https://github.com/IISHF/web2019/files/6000866/2021-02-27_.IISHF.Vision.Mission.Values_updated.docx)

**Comment by sgehrig** [comment]
We then need some more images please.

**Comment by sgehrig** [comment]
Should be fixed with #52
