### ISSUE TITLE
Members: Twitter "@" 

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#33]
for all Social Media profiles we depict "just" the organizational name, except for Twitter where an "@" is put before the organizational name. Any chance that we can organize the linking in a way that we do not depict the "@" on our website?
This would allow for a more consistent view of the org names over all social media channels.

**Comment by sgehrig** [comment]
The `@` is some sort of Twitter trademark. People are used to the `@handle` concept of Twitter. But changing it, is not problem.

**Comment by sgehrig** [comment]
@andrepoddubny Please note that all twitter profiles are now invalid (the `@` has to be removed now from all member profiles).

**Comment by andrepoddubny** [comment]
@sgehrig Just corrected all member country profiles. Thank you very much.
