### ISSUE TITLE
Committee: Title

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#36]
When creating a Committee Member the system allows to chose from "Chairman", "Vice Chairman" or Member. However, that does not result in a depiction on the frontend. Instead the word "Member" need be written in the "Title" to be depicted on the front end. 

I suggest deleting the "Title" element in the backend and depicting the "Member Type" on the frontend.

**Comment by sgehrig** [comment]
@andrepoddubny Can you please provide some screenshots? I didn't really get it.

**Comment by andrepoddubny** [comment]
@sgehrig When I a new committee member and select her/his status as "Member" this is not reflected on the website. (Please find a screen on back and front end attached). 

Only when I enter in "Title" the word "Member" it is being depicted on the frontend. 
![Screen Shot 2021-02-16 at 17 37 45](https://user-images.githubusercontent.com/41113334/108085703-4920ab00-707e-11eb-8938-7f71bbf4930d.png)
![Screen Shot 2021-02-16 at 17 38 18](https://user-images.githubusercontent.com/41113334/108085725-4f168c00-707e-11eb-8916-e183be36b206.png)

**Comment by sgehrig** [comment]
@andrepoddubny Ah. I see. Got it.

**Comment by sgehrig** [comment]
It's now clear that the `title` field is optional. If left empty, the default will be the title derived from the `member type`. The `title` still makes sense, because the chairman of the disciplinary committee is not called **Chairman** but **Disciplinary Officer**.
