### ISSUE TITLE
Committee: 

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#37]
It is a great idea to depict the duration of office on the website. However, I suggest that we organize it somewhat differently than currently. Right now it reads that Claes and you were nominated in 2017 for 2 years. That is true, but lastly you were nominated in 2019 for 2 years. 

We have two sets of data information. First, when a member was nominated. Secondly when the Chairman and Vice-Chairman were elected. 

As such I suggest we depict the year for all members since when they are "nominated" members of their committee. For the Chairman and Vice Chairman we should add in addition when they were "elected".

I suppose that Claes and you have a long standing history in the Technical Committee. I would not want to depict only 2 years. 

Lastly, the IISHF does not nominate Members of the Technical Committee. So, I would exclude that option from the backend for the Technical Committee.

**Comment by sgehrig** [comment]
> Lastly, the IISHF does not nominate Members of the Technical Committee. So, I would exclude that option from the backend for the Technical Committee.

The backend does not know what committees might be added. It's a very generic system to allow the setup of other committees as well. It's up to the administrator to specific the correct options for a member.

**Comment by andrepoddubny** [comment]
Dear Stefan, can you try this on yourself? In the front end only the latest term is shown. Not sure that we need the amount of terms. I prefer that  starting year, to say something like "Member since YEAR"
