### ISSUE TITLE
Members: Youtube Profile

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#39]
For ISHD and UFRH we have the Youtube channels and both countries have a Youtube Profile. 

ISHD     https://www.youtube.com/user/ISHDde
UFRH   https://www.youtube.com/channel/UCRlTdZ6mPmCgEzCZSZG13WQ

The Official profile of the Ukrainian is listed in Ukrainian language: Українська Федерація Хокею на Роликах
However, our back end does not recognize it. I suppose it is a language issue.

![Screen Shot 2021-02-16 at 21 44 38](https://user-images.githubusercontent.com/41113334/108113706-7ed68b80-70a0-11eb-99d7-9ea1b5be8ae7.png)

**Comment by sgehrig** [comment]
This is a YouTube profile link: `https://www.youtube.com/user/ISHDde`
And this is a YouTube channel link:
`https://www.youtube.com/channel/UCRlTdZ6mPmCgEzCZSZG13WQ`

For the first one the YouTube profile is `ISHDde` and for the second one the channel is `UCRlTdZ6mPmCgEzCZSZG13WQ`.
