### ISSUE TITLE
IISHF Organigram

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#41]
Dear Stefan, 

we have created an IISHF Organizational Structure. This is something we could publish in the section for the Presidium and the IISHF Officers. That is if that is anyhow possible. 

Please find in the enclosed zip file a PDF, PNG and Vector AI Version.

[IISHF Organization Structure.zip](https://github.com/IISHF/web2019/files/6032028/IISHF.Organization.Structure.zip)

**Comment by sgehrig** [comment]
We'll put the image on the IISHF public page with a link to download the PDF.
