### ISSUE TITLE
Facebook, Twitter, Instagram

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#43]
Facebook: https://www.facebook.com/iishf
Twitter: https://twitter.com/iishf
Twitter 2: https://twitter.com/iishf_live
Instagram: https://www.instagram.com/inlineskaterhockey/
Youtube: https://www.youtube.com/channel/UC8K38wviLbOa82VHemv_mGg (once we get to 100 subscriptions, we will get our own URL. 

We have 2 Twitter accounts. Basically one for the game results and one for general IISHF issues. That means, the one for general IISHF issues basically is being used for just the communication of the Communication Letters. I asked Erik if we do need both. I think that is not very practical...

Can you embed an Instagram feed? Yes. It's 100% possible to embed an Instagram feed into any website, as long as you have the login information for the Instagram account.

**Comment by sgehrig** [comment]
See #45, #46, #47 and #48

Facebook and Twitter is no problem. That's why they are scheduled for the MVP release. YouTube and Instagram might be more complicated.
