### ISSUE TITLE
Presidium / Staff Members / Committees

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#44]
Dear Stefan,

following thoughts:

Currently the menu items is called "Committees". If we depict more than just the Committees on this page, we need to change the menu name. I suggest to "Organization" (see https://www.iihf.com/en/statichub/4685/organization).

If Presidium, IISHF Officer and Committees are supposed to be on one page, than you need to add the Presidium. 

Staff Members -- Let's call them "IISHF Officers". In difference to the "Committees" I cannot publish a general picture for all Officers..Here we could add the organigram as a pictures, similarly to the Committees.

Committees - I removed all pictures and tried to update all members. I would prefer the following order of appearance:

1. Technical Committee
2. Disciplinary Committee 
3. Appeals Committee

**Comment by sgehrig** [comment]
@andrepoddubny We do not need to differentiate between regular officers and presidium members on the backend. Just make sure that every presidium member is available in the "Staff" administration with a role "presidium". I'll then make sure that all staff members with the "presidium" role will be displayed as the presidium on the IISHF public page.

**Comment by andrepoddubny** [comment]
I just just done so @sgehrig. Merci
