### ISSUE TITLE
Photos 1

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#49]
Dear Stefan,

the Photos on the main page are currently all "quadratic". Since photos in real life may have different formats the current set-up will cut pictures. Is there anything we can do about it?

**Comment by sgehrig** [comment]
@andrepoddubny Not sure who the design/layout reacts to images that are far off the current aspect ratio. We'll need to see.
For this slider style it makes sense however to keep a more or less "squarish" aspect ratio.
