### ISSUE TITLE
Photo 4 - Slider Main Page

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#52]
Dear Stefan, 

our designer needs technical parameters for the size of the "cut picture" to the slider. Is there any chance you can provide that?

**Comment by sgehrig** [comment]
@andrepoddubny What image are you talking about? The slider only uses regular images - not cut-outs.

**Comment by sgehrig** [comment]
@andrepoddubny Ah. You're referring to the top header slider.

**Comment by sgehrig** [comment]
@andrepoddubny Will check the sizes tomorrow.

**Comment by sgehrig** [comment]
That's the image: https://github.com/IISHF/web2019/blob/master/assets/img/main/slider-img.png

**Comment by sgehrig** [comment]
relates to #30

**Comment by sgehrig** [comment]
@andrepoddubny The size is (w × h): 655  ×  772 px.

**Comment by andrepoddubny** [comment]
Dear Stefan, please find two pictures for the slider (in addition to the Ukrainian player) in the below link. 
https://drive.google.com/drive/u/0/folders/12LS5eHNpiH9zNBpTHGAVYuSr-qYv19UD

Photo 1 and Photo 2 in two file versions.

**Comment by andrepoddubny** [comment]
Slide 1: 
IISHF Vision: Inline Skater Hockey is a well-developed sport recognized and played worldwide. Being the fastest and most physical summer team sport, it is independent from ice hockey and other roller sport disciplines. It remains affordable to its communities, and excites players, spectators and supporters of all sexes, abilities and age groups. Inline Skater Hockey seasons run throughout the entire year with official competitions lasting from early spring to early winter.

**Comment by andrepoddubny** [comment]
Slide 2: 
IISHF Mission: IISHF promotes, develops and safeguards inline skater hockey as a fascinating and fair team sport over all continents from street to elite level.

**Comment by andrepoddubny** [comment]
Slide 3: 
IISHF Values
•	Tolerance & Non-Discrimination
•	Sportsmanship, Fairness & Respect
•	Equality
•	Solidarity
•	Inclusion

**Comment by andrepoddubny** [comment]
Slide 4:
The IISHF organizes 7 European Cups  and 2 European Championships every year.

**Comment by sgehrig** [comment]
@andrepoddubny Which image to use for the 4th slide?

**Comment by andrepoddubny** [comment]
Dear Stefan, 

at the AGM 2021 a few corrections of the Vision, Mission and Values were undertaken. The final texts were approved as following:

Vision:

Inline Skater Hockey is a well-developed sport recognized and played worldwide. Being a physical game and the fastest summer team sport, it is independent from ice hockey and other roller sport disciplines. It remains accessible and affordable to its communities, and excites players, spectators and supporters of all genders, abilities and age groups. Inline Skater Hockey seasons run throughout the entire year with official competitions lasting from early spring to early winter.

Mission:

IISHF promotes, develops and safeguards inline skater hockey as a fascinating team sport over all continents from street to elite level.

Values: 

•	Inclusivity
•	Sportsmanship, Fairness & Respect
•	Equality
•	Solidarity
•	Integrity

Can you kindly update the Main Page of the new website?

**Comment by andrepoddubny** [comment]
Könntest du ggf. den Home Slider noch leicht inhaltliich anpassen? Zu dem habe ich ja keinen Zugang. 

Kannst du anstelle von „International Inline Skater Hockey Federation“ als Headline für die 4 Slides jeweils die Folgende Headline verwenden?
Slide 1.     IISHF Vision
Slide 2.    IISHF Mission
Slide 3.    IISHF Values
Slide 4.    IISHF Title Events

Zudem wäre es gut wenn zwischen Headline und Text eine freie Zeile bzw. etwas Abstand wäre. 

Den Text für Slide 4 - Title Event würde ich noch wie folgt anpassen:

IISHF organises every year 7 European Cups for Club teams (U13, U16, U19, Women, Men, Men Challenge, Veteran) and 2 European Championships (U19, Men).

**Comment by sgehrig** [comment]
@andrepoddubny Please do not add comments to closed issues because they cannot be found easily. Open a new issue if changes to closes tickets are required.
