### ISSUE TITLE
News 3 - News Headlines in the News "announcement" 

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#56]
Dear Stefan, 

currently the news announcement contains next to a picture, its Title (very small font letters) and the date of the news release also each Headline in full as an automated version. The way that this is arranged is quite unlucky, it is not quite clear and creates a visual overload. We'll have to better it.

**Comment by sgehrig** [comment]
@andrepoddubny please add screenshots when describing design problems. It's hard to locate the issues otherwise.

**Comment by andrepoddubny** [comment]
![Screen Shot 2021-02-26 at 10 41 03](https://user-images.githubusercontent.com/41113334/109276982-5fb5c780-781f-11eb-822d-bb8caaa3f3eb.png)

**Comment by sgehrig** [comment]
@andrepoddubny Indeed. That looks weird. It shows the subtitle there. Not very nice. will change that to display the title and show the tags instead of the title in the small bar above.
