### ISSUE TITLE
News - Text (Overlay and Font)

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#57]
Dear Stefan, 

the news text overlays with the picture on the right that is embedded in the site design. Plus the fond appears very small and different from the font we normally use. Do we use different fonts in our website or one standard font in different versions?

**Comment by sgehrig** [comment]
@andrepoddubny that's a good question. The fonts are the original ones used in the designs. I assume it's the same font everywhere, just in different sizes. 
Will check tomorrow.

**Comment by sgehrig** [comment]
The font size is the original one the designer used. But I agree, that it's too small. I'll adjust it.

![IISHF_2020-07-13_build_news-single html](https://user-images.githubusercontent.com/43394/109260149-e9549d80-77fd-11eb-94a2-2572be8b582b.png)
