### ISSUE TITLE
Main Site - Member Logo Slider 

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#61]
Ich habe einige Logos der NMA unter "Members" ausgetauscht. Hier insbesondere die Schweiz, GB und die Ukraine. Während das unter Members gut ausschaut, ist auf der Hauptseite jetzt der Slider "kaputt". Ich weiß leider nicht, wie ich das in Ordnung bringen kann.

**Comment by sgehrig** [comment]
@andrepoddubny Seems to be a problem with the CSS of the slider. Need to check that.

**Comment by sgehrig** [comment]
@andrepoddubny Please add the original file of the logo you uploaded.
