### ISSUE TITLE
News Articles - Update plus IISHF logo

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#62]
Dear Stefan, 

may I ask you to update the news articles for this year. 
In the last Article CL 2021-04 there is also a "?" in the "tag". In addition with every news entry comes the IISHF logo in poor quality. Any chance we can either delete the IISHF logo or replace it? I added a 72 dpi IISHF logo in .png format which I received from a designer to be used for website purposes this week. 

![IISHF Logo 72 dpi](https://user-images.githubusercontent.com/41113334/118022443-0b71ac80-b365-11eb-880b-ef817316c3fa.png)

**Comment by sgehrig** [comment]
The issue with the `?` in legacy articles will be fixed when we finally migrate the old news articles.
