### ISSUE TITLE
NMA + IISHF Logos

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#66]
Ciao Stefan,

du hast unter Punkt "Main Site - Member Logo Slide" geschrieben, dass ich alle Logos im Originalformat hinzufügen möge. 
Ich habe jetzt auch das neue israelische Logo erhalten. Alle Logos sind jetzt auf DropBox in zwei Ordnern (Präsidium, Marketing). Soll ich dir zum Logo Ordner im Marketing Ordner Zugang geben?

**Comment by sgehrig** [comment]
@andrepoddubny That's already fixed. The issue was related to some missing CSS for the images in the members slider.
